version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
      - ./data:/data  
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/tasks.db
